# Generated by Django 3.2.20 on 2024-01-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20240127_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='Floor_Plans',
            field=models.ImageField(upload_to='media/Property/images'),
        ),
    ]
