# Generated by Django 3.2.20 on 2023-10-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_property_property_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=500)),
                ('phone_Number', models.IntegerField(max_length=14)),
                ('Message', models.TextField()),
            ],
        ),
    ]
