# Generated by Django 3.2.20 on 2023-12-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_cell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Cell',
            field=models.CharField(default='none', max_length=11),
        ),
    ]
