# Generated by Django 3.2.20 on 2024-01-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_property_floor_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleviewing',
            name='mobile_Number',
            field=models.BigIntegerField(default='+880'),
        ),
    ]
