# Generated by Django 3.2.20 on 2023-10-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_Number',
            field=models.BigIntegerField(max_length=14),
        ),
    ]
