# Generated by Django 3.2.20 on 2023-12-14 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_contact_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Cell',
        ),
    ]
