# Generated by Django 3.2.20 on 2023-10-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_Number',
            field=models.BigIntegerField(max_length=14, unique=True),
        ),
    ]
