# Generated by Django 3.2.20 on 2023-12-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_contact_cell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_Number',
            field=models.CharField(max_length=12),
        ),
    ]
