# Generated by Django 3.2.20 on 2023-10-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_contact_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.URLField(max_length=1000)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('desc', models.CharField(default='', max_length=25015)),
                ('athour', models.CharField(max_length=1023)),
                ('slug', models.CharField(max_length=130)),
                ('TimeStamp', models.DateTimeField(null=True)),
            ],
        ),
    ]
