# Generated by Django 3.2.20 on 2023-10-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='image10',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='image2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='image3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='image4',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='image5',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='image6',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='image7',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='image8',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='image9',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
