# Generated by Django 3.2.20 on 2023-12-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_Number',
            field=models.CharField(max_length=11),
        ),
    ]
