# Generated by Django 3.2.20 on 2023-12-14 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_contact_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleviewing',
            old_name='property',
            new_name='Property',
        ),
    ]
