# Generated by Django 3.2.20 on 2023-10-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20231027_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('employee_Name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=500)),
                ('mobile_Number', models.BigIntegerField(max_length=14, unique=True)),
                ('experience', models.IntegerField(default='Years', max_length=2)),
            ],
        ),
    ]
