# Generated by Django 3.2.20 on 2023-12-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_property_scheduleviewing_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialInterior',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=500)),
                ('phone_Number', models.CharField(max_length=11)),
                ('floor_Area', models.CharField(default='sqft', max_length=200)),
                ('ideas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Residentialinterior',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=500)),
                ('phone_Number', models.CharField(max_length=11)),
                ('floor_Area', models.CharField(default='sqft', max_length=200)),
                ('ideas', models.TextField()),
            ],
        ),
    ]
