# Generated by Django 3.2.20 on 2024-03-07 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
    ]
