# Generated by Django 3.2.20 on 2023-10-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20231027_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='experience',
            field=models.IntegerField(default='Years'),
        ),
    ]
