# Generated by Django 3.2.20 on 2024-03-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_user_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verified',
            new_name='email_verified',
        ),
    ]
