# Generated by Django 3.2.20 on 2023-10-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_services_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Baths',
            field=models.CharField(default='Baths', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='Beds',
            field=models.CharField(default='Beds', max_length=200),
        ),
    ]
