# Generated by Django 3.2.20 on 2023-10-31 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20231031_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='image10',
            new_name='Floor_Plans',
        ),
    ]
