# Generated by Django 3.2.20 on 2023-10-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_image10_property_floor_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('Office', 'Office')], default='', max_length=100),
        ),
    ]
