# Generated by Django 3.2.20 on 2023-10-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
