# Generated by Django 3.2.20 on 2023-11-01 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_property_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleViewing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('TIME_CHOICES', models.CharField(choices=[('9:00 AM - 12:00 PM', '9:00 AM - 12:00 PM'), ('2:00 PM - 5:00 PM', '2:00 PM - 5:00 PM'), ('5:00 PM - 8:00 PM', '5:00 PM - 8:00 PM')], default='', max_length=100)),
                ('name', models.CharField(default='', max_length=255)),
                ('mobile_Number', models.BigIntegerField(default='', unique=True)),
                ('email', models.EmailField(default='', max_length=500)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.property')),
            ],
        ),
    ]
