# Generated by Django 3.2.20 on 2023-11-01 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20231101_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleviewing',
            name='property',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.property'),
        ),
    ]
