# Generated by Django 3.2.20 on 2024-02-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_auto_20240202_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='user_type',
            field=models.CharField(max_length=255),
        ),
    ]
