from django.urls import path
from .views import *
urlpatterns = [
    path('register/', UserRegistrationAPIView.as_view(), name='register'),
    path('verify-email/', VerifyEmailAPIView.as_view(), name='verify_email'),
    path('resend-verification-email/', ResendVerificationEmailAPIView.as_view(), name='resend-verification-email'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('userprofile/', UserProfileView.as_view(), name='userprofile'),
    path('update_profile/<str:pk>/', UpdateProfileView.as_view(), name='auth_update_profile'),
    path('changepassword/', UserChangePasswordView.as_view(), name='changepassword'),
    path('send-reset-password-email/', SendPasswordResetEmailView.as_view(), name='send-reset-password-email'),
    path('reset-password/<email>/<token>/', UserPasswordResetView.as_view(), name='reset-password'),
    path('Property/', PropertyList.as_view()),#
    path('Property/<str:pk>/', PropertyDetail.as_view()),
    path('Contact/feedback', ContactAPIView.as_view()),
    path('propertyinfo/', PropertyInfoAPIView.as_view()),
    path('propertyinfo/<int:pk>/', PropertyInfoDEtails.as_view()),
    path('Post/', PostList.as_view()),
    path('Post/<int:pk>/', PostDetail.as_view()),
    path('Services/', ServicesListAPIView.as_view()),
    path('ScheduleViewing/', ScheduleViewingAPIView.as_view()),
    path('Residentialinterior/ResidentialinteriorContact', ResidentialinteriorAPIView.as_view()),
    path('Commercialinterior/CommercialInteriorContact', CommercialInteriorAPIView.as_view()), 
    path('ResidentialArchitecture/ResidentialArchitectureContact', ResidentialArchitectureAPIView.as_view()),
    path('CommercialArchitecture/CommercialArchitectureContact', CommercialArchitectureAPIView.as_view()), 
    path('bank_details/', bank_detailsListAPIView.as_view()),
    path('apply_for_loan/bank', Apply_For_LoanAPIView.as_view()),
    path('properties-search/', PropertySearchAPIView.as_view(), name='property-search'),
    path('requestForAddProperty/requestinfo', requestForAddPropertyAPIView.as_view()),
    path('JobOpening/', JobOpeningList.as_view()),
    path('JobOpening/<str:pk>/', JobOpeningDetail.as_view()),
    path('apply_for_job/', ApplyJobAPIView.as_view()),
    path('notification/', notificationList.as_view()),
    path('notification/<int:pk>/', notificationDetail.as_view()),
    path('mark_notification_as_seen/<int:id>/', MarkNotificationAsSeen.as_view(), name='mark_notification_as_seen'),
    path('unseen_notification_count/', UnseenNotificationCount.as_view(), name='unseen_notification_count'),
    path('mark_PropertyInfo_as_seen/<int:id>/', MarkPropertyInfoAsSeen.as_view(), name='mark_PropertyInfo_as_seen'),
    path('unseen_propertyinfo_count/', UnseenPropertyInfoCount.as_view(), name='unseen_PropertyInfo_count'),
    path('delete_user/', delete_user, name='delete_user'),
    path('delete_request_add_property/<int:id>/', delete_requestaddproperty, name='delete_request_add_property'),
    path('delete_property/<str:Reference_number>/', delete_property, name='delete_property'),
    path('delete_notification/<int:id>/', delete_notification, name='delete_notification'),
    path('delete_propertyinfo/<int:propertyId>/', delete_propertyInfo, name='delete_propertyinfo'),
]